### ISSUE TITLE
Use of Self

### ISSUE THREAD

**Issue by InderKumarRathore** [raywenderlich/swift-style-guide#289] opened 2018-01-02 07:49 UTC
>Use of Self

>For conciseness, avoid using self since Swift does not require it to access an object's properties or invoke its methods.

>Use self only when required by the compiler (in @escaping closures, or in initializers to disambiguate properties from arguments). In other words, if it compiles without self then omit it.

I think accessing instance variable with self provides more readability.

e.g. 

```
func someMethod() {
  // Code code code
  self.order = orders[0]
  // Code code code
}
```
In above code it's clear that **order** variable is instance var not a local var.

**Comment by RobertGummesson** [comment] 2018-01-02 09:02
Possible duplicate of #288.

**Comment by JRG-Developer** [comment] 2018-01-02 09:03
This is a duplicate of

https://github.com/raywenderlich/swift-style-guide/issues/288

wherein the reasons for _not_ using `self` were justified.

**Closed by JRG-Developer** 2018-01-02 09:03 UTC
